name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Generate GitHub contribution graph snake animation
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.actor }}
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Set Output
        run: echo "snake_gif_path=dist/github-contribution-grid-snake.gif" >> $GITHUB_ENV
      - name: Set Output
        run: echo "snake_svg_path=dist/github-contribution-grid-snake.svg" >> $GITHUB_ENV

      - name: Modify Permissions
        run: sudo chown -R $USER:$USER dist

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Resize SVG File
        run: |
          convert -background none -resize 100% dist/github-contribution-grid-snake.svg dist/resized-github-contribution-grid-snake.png

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Push svg files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
